name: docs

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install pipenv
      - run: pipenv sync
      - run: pipenv run python tools/build.py
      - run: pipenv run mkdocs gh-deploy --force
